// Technology Predictions Data
const techPredictions = [
  {
    technology: "AI-Powered Crop Monitoring",
    type: "Monitoring",
    description: "Advanced AI systems for real-time crop health monitoring using drones and sensors",
    confidence: 85,
    targetYear: 2025,
    weather: "moderate",
    area: "all",
    landType: "all",
    state: "All States",
    impact: "Increase yield by 20-30% through early disease detection",
    implementation: "Install sensors and AI monitoring systems",
    cost: "₹50,000 - ₹2,00,000 per acre",
    timeline: "6-12 months"
  },
  {
    technology: "Smart Irrigation Systems",
    type: "Irrigation",
    description: "IoT-based irrigation systems that optimize water usage based on soil moisture",
    confidence: 90,
    targetYear: 2024,
    weather: "dry",
    area: "all",
    landType: "irrigated",
    state: "Maharashtra, Karnataka, Tamil Nadu",
    impact: "Reduce water consumption by 40-60%",
    implementation: "Deploy soil moisture sensors and automated irrigation",
    cost: "₹30,000 - ₹1,50,000 per acre",
    timeline: "3-6 months"
  },
  {
    technology: "Precision Agriculture Drones",
    type: "Monitoring",
    description: "Drones equipped with multispectral cameras for crop analysis",
    confidence: 88,
    targetYear: 2024,
    weather: "moderate",
    area: "all",
    landType: "all",
    state: "Punjab, Haryana, Uttar Pradesh",
    impact: "Improve crop management efficiency by 35%",
    implementation: "Regular drone surveys and data analysis",
    cost: "₹1,00,000 - ₹5,00,000 per farm",
    timeline: "1-3 months"
  },
  {
    technology: "Vertical Farming Systems",
    type: "Production",
    description: "Indoor vertical farming for year-round crop production",
    confidence: 75,
    targetYear: 2026,
    weather: "all",
    area: "urban",
    landType: "controlled",
    state: "Delhi, Mumbai, Bangalore",
    impact: "10x higher yield per square foot",
    implementation: "Build vertical farming facilities",
    cost: "₹50,00,000 - ₹2,00,00,000 per facility",
    timeline: "12-18 months"
  },
  {
    technology: "Climate-Resilient Seeds",
    type: "Genetics",
    description: "Genetically modified seeds resistant to extreme weather conditions",
    confidence: 82,
    targetYear: 2025,
    weather: "hot",
    area: "south",
    landType: "rainfed",
    state: "Andhra Pradesh, Telangana, Karnataka",
    impact: "Maintain yield under extreme weather",
    implementation: "Replace traditional seeds with climate-resilient varieties",
    cost: "₹200 - ₹500 per kg",
    timeline: "Immediate"
  },
  {
    technology: "Blockchain Supply Chain",
    type: "Logistics",
    description: "Blockchain technology for transparent agricultural supply chain",
    confidence: 78,
    targetYear: 2025,
    weather: "all",
    area: "all",
    landType: "all",
    state: "All States",
    impact: "Increase farmer income by 15-25%",
    implementation: "Implement blockchain tracking system",
    cost: "₹10,000 - ₹50,000 per farmer",
    timeline: "6-12 months"
  },
  {
    technology: "Solar-Powered Cold Storage",
    type: "Storage",
    description: "Solar-powered cold storage units for perishable crops",
    confidence: 85,
    targetYear: 2024,
    weather: "hot",
    area: "all",
    landType: "all",
    state: "Maharashtra, Gujarat, Madhya Pradesh",
    impact: "Reduce post-harvest losses by 30-40%",
    implementation: "Install solar cold storage units",
    cost: "₹5,00,000 - ₹20,00,000 per unit",
    timeline: "3-6 months"
  },
  {
    technology: "Robotic Harvesting",
    type: "Automation",
    description: "Automated robots for harvesting fruits and vegetables",
    confidence: 70,
    targetYear: 2026,
    weather: "moderate",
    area: "all",
    landType: "irrigated",
    state: "Maharashtra, Karnataka, Tamil Nadu",
    impact: "Reduce labor costs by 50-60%",
    implementation: "Deploy harvesting robots",
    cost: "₹20,00,000 - ₹50,00,000 per robot",
    timeline: "12-18 months"
  },
  {
    technology: "Soil Health Monitoring",
    type: "Monitoring",
    description: "Advanced soil sensors for real-time nutrient and pH monitoring",
    confidence: 88,
    targetYear: 2024,
    weather: "all",
    area: "all",
    landType: "all",
    state: "All States",
    impact: "Optimize fertilizer usage by 25-35%",
    implementation: "Install soil monitoring sensors",
    cost: "₹15,000 - ₹75,000 per acre",
    timeline: "1-3 months"
  },
  {
    technology: "Hydroponic Farming",
    type: "Production",
    description: "Soilless farming using nutrient-rich water solutions",
    confidence: 80,
    targetYear: 2025,
    weather: "all",
    area: "urban",
    landType: "controlled",
    state: "Delhi, Mumbai, Bangalore, Hyderabad",
    impact: "3-5x higher yield with 90% less water",
    implementation: "Set up hydroponic systems",
    cost: "₹2,00,000 - ₹10,00,000 per setup",
    timeline: "6-12 months"
  },
  {
    technology: "Weather Prediction AI",
    type: "Prediction",
    description: "AI-powered weather prediction for agricultural planning",
    confidence: 85,
    targetYear: 2024,
    weather: "all",
    area: "all",
    landType: "all",
    state: "All States",
    impact: "Improve crop planning accuracy by 40%",
    implementation: "Deploy weather prediction AI systems",
    cost: "₹50,000 - ₹2,00,000 per district",
    timeline: "3-6 months"
  },
  {
    technology: "Organic Pest Control",
    type: "Protection",
    description: "Biological pest control methods using natural predators",
    confidence: 75,
    targetYear: 2024,
    weather: "moderate",
    area: "all",
    landType: "organic",
    state: "Kerala, Karnataka, Tamil Nadu",
    impact: "Reduce pesticide use by 60-80%",
    implementation: "Introduce beneficial insects and natural predators",
    cost: "₹5,000 - ₹25,000 per acre",
    timeline: "Immediate"
  },
  {
    technology: "Smart Greenhouses",
    type: "Production",
    description: "Automated greenhouses with climate control systems",
    confidence: 82,
    targetYear: 2025,
    weather: "cold",
    area: "north",
    landType: "controlled",
    state: "Himachal Pradesh, Uttarakhand, Jammu & Kashmir",
    impact: "Year-round production in cold regions",
    implementation: "Build automated greenhouse facilities",
    cost: "₹10,00,000 - ₹50,00,000 per greenhouse",
    timeline: "6-12 months"
  },
  {
    technology: "Mobile App for Farmers",
    type: "Digital",
    description: "Comprehensive mobile applications for agricultural guidance",
    confidence: 90,
    targetYear: 2024,
    weather: "all",
    area: "all",
    landType: "all",
    state: "All States",
    impact: "Improve decision-making and access to information",
    implementation: "Develop and deploy mobile applications",
    cost: "₹1,000 - ₹5,000 per farmer",
    timeline: "3-6 months"
  },
  {
    technology: "Biofuel Production",
    type: "Energy",
    description: "Production of biofuels from agricultural waste",
    confidence: 70,
    targetYear: 2026,
    weather: "all",
    area: "all",
    landType: "all",
    state: "Maharashtra, Karnataka, Tamil Nadu",
    impact: "Generate additional income from waste",
    implementation: "Set up biofuel production units",
    cost: "₹50,00,000 - ₹2,00,00,000 per unit",
    timeline: "12-18 months"
  }
];

module.exports = techPredictions; 